pipeline {
    agent any

          tools {
    jdk 'jdk21'
}
    
    environment {
        IMAGE_NAME = "java-maven-app"
        CONTAINER_NAME = "java-app-container"
    }

    stages {

        stage('Clone Code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/ayeshactl/demo-maven-project.git'           
            }
        }
stage('Build Maven App') {
    steps {
        sh '''
        echo "PATH BEFORE FIX:"
        echo $PATH

        export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
        export PATH=/usr/lib/jvm/java-21-openjdk-amd64/bin:/usr/bin:/bin

        echo "JAVA VERSION:"
        java -version

        echo "MAVEN VERSION:"
        mvn -v

        mvn clean package
        '''
    }
}

        stage('Docker Build Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME .'
            }
        }

        stage('Stop Old Container') {
            steps {
                sh '''
                docker stop $CONTAINER_NAME || true
                docker rm $CONTAINER_NAME || true
                '''
            }
        }

        stage('Run Container') {
            steps {
                sh '''
                docker run -d -p 8081:8080 --name $CONTAINER_NAME $IMAGE_NAME
                '''
            }
        }
    }
}
