pipeline {
    agent any

    stages {

        stage('Build Maven App') {
            steps {
                sh '''
                java -version
                mvn -v
                mvn clean package
                '''
            }
        }
